//----------------------------------USER AUTH
export const ADD_TOKEN = 'ADD_TOKEN';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';

//----------------------------------USERS
export const ADD_USERS = 'ADD_USERS';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FAILED = 'USERS_FAILED';

//----------------------------------INGREDIENT
export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENTS = 'DELETE_INGREDIENTS';
export const INGREDIENTS_LOADING = 'INGREDIENTS_LOADING';
export const INGREDIENTS_FAILED = 'INGREDIENTS_FAILED';

//----------------------------------GROCERIES
export const ADD_GROCERIES = 'ADD_GROCERIES';
export const DELETE_GROCERIES = 'DELETE_GROCERIES';
export const GROCERIES_LOADING = 'GROCERIES_LOADING';
export const GROCERIES_FAILED = 'GROCERIES_FAILED';
export const ADD_GROCERY = 'ADD_GROCERY';
export const TOGGLE_GROCERY = 'TOGGLE_GROCERY';
export const TOGGLE_FETCH_GROCERY = 'TOGGLE_FETCH_GROCERY';

//----------------------------------NUTRITION
export const ADD_NUTRITIONS = 'ADD_NUTRITIONS';
export const ADD_NUTRITION = 'ADD_NUTRITION';
export const DELETE_NUTRITION = 'DELETE_NUTRITION';
export const NUTRITION_LOADING = 'NUTRITION_LOADING';
export const NUTRITION_FAILED = 'NUTRITION_FAILED';

//----------------------------------RECIPENUTRITION
export const ADD_RECIPENUTRITION = 'ADD_RECIPENUTRITION';
export const EDIT_RECIPENUTRITION = 'EDIT_RECIPENUTRITION';
export const DELETE_RECIPENUTRITION = 'DELETE_RECIPENUTRITION';
export const RECIPENUTRITION_LOADING = 'RECIPENUTRITION_LOADING';
export const RECIPENUTRITION_FAILED = 'RECIPENUTRITION_FAILED';

//----------------------------------RECIPE
export const ADD_RECIPE = 'ADD_RECIPE';
export const EDIT_RECIPE = 'EDIT_RECIPE';
export const SEARCH_RECIPE = 'SEARCH_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const RECIPE_LOADING = 'RECIPE_LOADING';
export const RECIPE_FAILED = 'RECIPE_FAILED';

export const ADD_IMAGE = 'ADD_IMAGE';


//----------------------------------RECIPESTEPS
export const ADD_RECIPESTEPS = 'ADD_RECIPESTEPS';
export const EDIT_RECIPESTEPS = 'EDIT_RECIPESTEPS';
export const DELETE_RECIPESTEPS = 'DELETE_RECIPESTEPS';
export const RECIPESTEPS_LOADING = 'RECIPESTEPS_LOADING';
export const RECIPESTEPS_FAILED = 'RECIPESTEPS_FAILED';

//----------------------------------RECIPETAGS
export const ADD_RECIPETAGS = 'ADD_RECIPETAGS';
export const EDIT_RECIPETAGS = 'EDIT_RECIPETAGS';
export const DELETE_RECIPETAGS = 'DELETE_RECIPETAGS';
export const RECIPETAGS_LOADING = 'RECIPETAGS_LOADING';
export const RECIPETAGS_FAILED = 'RECIPETAGS_FAILED';

//----------------------------------RECIPEINGREDIENTS
export const ADD_RECIPEINGREDIENTS = 'ADD_RECIPEINGREDIENTS';
export const ADD_RECIPEINGREDIENT = 'ADD_RECIPEINGREDIENT';
export const EDIT_RECIPEINGREDIENTS = 'EDIT_RECIPEINGREDIENTS';
export const DELETE_RECIPEINGREDIENTS  = 'DELETE_RECIPEINGREDIENTS';
export const RECIPEINGREDIENTS_LOADING = 'RECIPEINGREDIENTS_LOADING';
export const RECIPEINGREDIENTS_FAILED = 'RECIPEINGREDIENTS_FAILED';

//----------------------------------MEALPLAN
export const ADD_MEALPLAN = 'ADD_MEALPLAN';
export const DELETE_MEALPLAN = 'DELETE_MEALPLAN';
export const MEALPLAN_LOADING = 'MEALPLAN_LOADING';
export const MEALPLAN_FAILED = 'MEALPLAN_FAILED';

//----------------------------------MEALPLANCOLLECTION
export const ADD_MEALPLANCOLLECTION = 'ADD_MEALPLANCOLLECTION';
export const MEALPLANCOLLECTION_LOADING = 'MEALPLANCOLLECTION_LOADING';
export const MEALPLANCOLLECTION_FAILED = 'MEALPLANCOLLECTION_FAILED';

//----------------------------------COMMENTS
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETECOMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const EDIT_COMMENT = 'EDIT_COMMENT';